// <auto-generated />
namespace SMS.DATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class adding_more_modules_in_student : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_more_modules_in_student));
        
        string IMigrationMetadata.Id
        {
            get { return "202006050955067_adding_more_modules_in_student"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
