// <auto-generated />
namespace SMS.DATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Add_field_in_different_modules : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_field_in_different_modules));
        
        string IMigrationMetadata.Id
        {
            get { return "202006100929502_Add_field_in_different_modules"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
