// <auto-generated />
namespace SMS.DATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addedisSent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedisSent));
        
        string IMigrationMetadata.Id
        {
            get { return "202302171701368_added-isSent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
